<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <header>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="/bootstrap/3.2.0/css/bootstrap.min.css" />
        <!-- Optional theme -->
        <link rel="stylesheet" href="/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
        <!-- Latest compiled and minified JavaScript -->
        <script src="/bootstrap/3.2.0/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="/css.css" />
    </header>
    <body>
        <div class="container">
            <div class="row">

                <div class="panel panel-primary">
                    <div class="panel-heading">phpDBMapper - DB access</div>
                    <div class="panel-body">

                        <div class="alert alert-info" role="alert">
                            <strong>Status: </strong> <?php echo $this->status ; ?>
                        </div>
                        
                        <?php echo $this->form ;?>
                    
                    </div>
                </div>

            </div>
        </div>
    </body>
</html>