        <div class="container">
            <div class="row">

                <div class="panel panel-primary">
                    <div class="panel-heading"><strong>phpDBMapper - MySQL database mapper</strong></div>
                    <div class="panel-body">

                        <div class="alert alert-info" role="alert">
                            <strong>Status: </strong> <?php echo $this->status ; ?>
                        </div>
                        
                        <?php echo $this->form ;?>
                    
                    </div>
                </div>

            </div>
        </div>
