<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <script src="/frontend/jquery.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/bootstrap/3.2.0/css/bootstrap.min.css" />
    <!-- Optional theme -->
    <link rel="stylesheet" href="/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <!-- Latest compiled and minified JavaScript -->
    <script src="/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/frontend/css.css" />
    <script src="/frontend/js.js"></script>
</head>
<body>

    <?php echo $this->layout()->content; ?>

</body>
</html>